name: Ecomerce Automation

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into the server and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SWARM_MANAGER_HOST }}
          username: ${{ secrets.SWARM_HOST_USERNAME }}
          key: ${{ secrets.DOCKER_KEY }}
          port: ${{ secrets.SWARM_HOST_SSH_PORT }}
          script: |
            cd ~/ecomerce

            echo "Resetting git repository..."
            git fetch origin main
            git checkout main
            git reset --hard origin/main

            echo "Rebuilding Docker containers..."
            # Remove all stopped containers, networks, images, and cache
            sudo docker system prune -a --volumes -f
            sudo docker-compose down --volumes --remove-orphans
            sudo docker-compose build --no-cache
            sudo docker-compose up -d
